CREATE TABLE Accounts(
AccountID NUMBER PRIMARY KEY,
AccountTYPE VARCHAR2(20),
Balance NUMBER
);

CREATE TABLE Employees(
EmployeeID NUMBER PRIMARY KEY,
Name VARCHAR2(30),
Department VARCHAR2(20),
Salary NUMBER
);