CREATE TABLE Customers(
CustomerID NUMBER PRIMARY KEY,
Name VARCHAR2(30),
Age NUMBER,
Balance NUMBER,
IsVIP VARCHAR2(1)
);

CREATE TABLE Loans(
LoanID NUMBER PRIMARY KEY,
CustomerID NUMBER,
InterestRate NUMBER,
DueDate DATE
);